### ISSUE TITLE
 Keyboard shortcut not working on startup

### ISSUE THREAD

**Issue by rparrapy** [DavidLGoldberg/jumpy#100]
Steps to reproduce:
1. Open Atom.
1. Open any file.
1. Press <kbd>shift</kbd>+<kbd>enter</kbd> (nothing happens).

How to solve (manually):
1. Toggle jumpy through <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> -> "Jumpy: Toggle".
1. In Atom settings, disable Jumpy and enable it again.
1. It works!

I am using Atom 1.13.1 and macOS Sierra.

**Comment by DavidLGoldberg** [comment]
I'm on El Capitan still.

I think I still have a restraint where you have to reload atom after install.  A bunch of packages used to have similar requirements.  That may be changing shortly.

control+alt+command+l (as in "load" ....lower case L) reloads Atom.  That's all you should have to do after installing Jumpy.

I'll leave this open as a bug until I can test it a few times.  Also upgrading to Sierra soon, in case it's something weird there, but I doubt it.

**Comment by DavidLGoldberg** [comment]
I put it as minor since I haven't really seen this come up before.  Be interesting to see if this becomes more common.  I'm currently working on a big refactor though so this will have to wait a bit.

**Comment by DavidLGoldberg** [comment]
Is this still an issue, I should have mentioned earlier, you really need to check
<kbd>cmd</kbd>+<kbd>.</kbd> To look at what's catching the key.  Let me know if you've solved this, or this helps, closing the issue for now since no new reports.

Feel free to let me know / keep the convo going on this thread though!
