### ISSUE TITLE
Doesn't work with the "Shadow DOM" flag enabled.

### ISSUE THREAD

**Issue by pilwon** [DavidLGoldberg/jumpy#42]
This package doesn't seem to work properly with the new "Shadow DOM" feature. It doesn't display the shortcut keys. When `shift + enter` is pressed.

Please refer to http://blog.atom.io/2014/11/18/avoiding-style-pollution-with-the-shadow-dom.html

**Comment by DavidLGoldberg** [comment]
Thanks so much for letting me know.  I've been working in a branch for this.  I'll push this out tomorrow.

**Comment by DavidLGoldberg** [comment]
Oh, you scared me.  I thought they went live with the default push.  Still, it's on it's way!

**Comment by pilwon** [comment]
@DavidLGoldberg It's great to hear the fix is on the way. Love your package. Thanks-

**Comment by DavidLGoldberg** [comment]
Thanks! :+1:

**Comment by trkoch** [comment]
Shadow DOM is now enabled by default. Thanks for working on this.

**Comment by DavidLGoldberg** [comment]
I'll guess I'll have to rush this out!  I didn't see any notification on the blog or stuff that it was coming so soon!  I'll try to rush this out tonight.  I think I'll have to temporarily disable / break the beacon feature as this was breaking due to shadow dom + animation keyframes.  Still working on a fix for *that*.

**Comment by DavidLGoldberg** [comment]
@pilwon @trkoch , I launched 2.0.0.  This fixes shadow dom and updates almost every LOC, it uses the new ATOM API, no deprecations.  See the changelog for some more details..

**Comment by trkoch** [comment]
Thanks! I haven't noticed any issues so far. :+1:
