### ISSUE TITLE
Find and jumpy

### ISSUE THREAD

**Issue by terraqout** [DavidLGoldberg/jumpy#76]
Hi all, thanks for your work on this plugin.
But what I expect from plugin like this (vimium, easymotion) I can search on page and jump only between filtered strings. I tried to change pattern in settings and this work as it should for me. But there is no any popup window or better integration with default-find-replace plugin.
If this feature would be accepted I can implement it by myself.

Thanks for answer

**Comment by DavidLGoldberg** [comment]
Thanks for your interest.

I have to get back to you on this one later.  But the short answer is I don't think I want to complicate this plugin too much.

The goal wasn't to make easymotion at all.  I started this idea a long time ago before I knew of it.  I use vimium.  I actually found out about it from a Jumpy user!  I love vimium!  It seems to take the same philosophy as Jumpy for the most part.

Which part of vimium do you want to emulate?

**Comment by DavidLGoldberg** [comment]
If you read the open issues and pull requests there are a few more directions where I, and some of the users, want this to go in the future.

I've been a little busy but should get back into it pretty soon (I'm overdue for some Jumpy coding).

Check the other issues / PR, but for instance, We were thinking of getting rid of the regex all together, and adding in end of line and beginning, and handling symbols better.

**Comment by terraqout** [comment]
> Which part of vimium do you want to emulate?
Just links hinting. When you press 'f', type part of word and it used to filter all active links on page. Same way as easymotion does.
I had changed pattern to any word and it works like a filter. That was exactly what I want, except way to change pattern on the fly (incorporated with find-search or just binded to '/')

**Comment by DavidLGoldberg** [comment]
Ok, so to be clear you basically want easymotion.  I don't want this for Jumpy at all.   I think there's a package doing this.  I think it's too complicated.  Eventually, I want to get around to catching more end of lines, empty lines, braces etc.  But I do not want to do a 2 phased jump.  I think that's too complicated.  I use vim-mode, so I use / all of the time for search.  The point of Jumpy is to replace the mouse, when you see it on the screen.  Especially helpful for larger screens.

I don't see how vimium does anything different than Jumpy.  I use the f functionality in vimium all the time.  I learned of vimium, because a Jumpy user said it was just like it.  I love vimium, use it all the time and don't see what Jumpy is missing in that regard.

The only thing that vimium *can* do is the single char links.  Anything with over 26 words would need more.. and I don't want to get into edge cases for super small files.

I'm closing this as an issue, but please feel free to keep the discussion going.
